[package]
name = "rc-zip"
version = "1.0.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"
description = "zip reading and writing"
repository = "https://github.com/rust-compress/rc-zip"
readme = "README.md"
license = "Apache-2.0 OR MIT"

keywords = ["zip", "unzip"]
categories = ["compression"]

[badges]
travis-ci = { repository = "rust-compress/rc-zip" }
maintenance = { status = "experimental" }

[profile.dev]
opt-level = 0
debug = true

[profile.release]
debug = true

[dependencies]
nom = "5.0.0"
pretty-hex = "0.1.0"
hex_fmt = "0.3.0"
circular = "0.3.0"
chrono = "0.4.7"
chardet = "0.2.4"
encoding_rs = "0.8.17"
codepage-437 = "0.1.0"
log = "0.4.7"
crc32fast = "1.2.0"
positioned-io = { version = "0.2.2", optional = true }
libflate = { version = "0.1.25", optional = true }
ara = { git = "https://github.com/JetASAP/ara", branch = "main", optional = true }
async-trait = { version = "0.1.36", optional = true }
futures = { version = "0.3.5", optional = true }
async-compression = { version = "0.3.5", optional = true }

[dev-dependencies]
color-backtrace = "0.2.2"
env_logger = "0.6.2"
ubio = { version = "0.1.0" }
tokio = "0.2.22"

[features]
default = ["sync", "async-ara"]
sync = ["positioned-io", "libflate"]
async-ara = ["ara", "async-trait", "futures", "async-compression", "async-compression/futures-io", "async-compression/deflate"]

[workspace]
members = [ ".", "samples/jean" ]
default-members = [ ".", "samples/jean" ]

